language: python
python:
  - 2.7
  - 3.6
  - 3.7
  - 3.8
  - pypy
install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
  - pip install coveralls
script:
  - coverage run --source=slumber setup.py test
after_success:
  - coveralls
